name: False Positive Report
description: Report benign input that ZugaShield incorrectly blocks
title: "[FP] "
labels: ["false-positive", "bug"]
body:
  - type: textarea
    id: input
    attributes:
      label: Blocked input
      description: The benign input that was incorrectly flagged
    validations:
      required: true

  - type: textarea
    id: decision
    attributes:
      label: ZugaShield decision
      description: "Paste the decision details (verdict, threats_detected, layer)"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ZugaShield version
      placeholder: "1.0.0"
